[project]
name = "archipelagrub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.1",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]
